### ISSUE TITLE
First review

### ISSUE THREAD

**Issue by masangana** [ElsonOtake/Osesp#3]
### @ElsonOtake 

Very great job. Very impressed. Your code is clear and clean. The result very interesting. 
If I may allow myself an opinion:

- The navigation menu, the footer, and the sponsor section are the same for all pages, instead of copy pasting, you can use JS to make it more dynamic. This avoids copying the same code.
- avoid long lines of code as best as possible to facilitate the readability of your code
- Your navigation menu should be inside the `<nav>` instead of a `div`
- There are some empty `div` in your page.
- You should also update your github page setting. To put your source file to master branch

**Comment by NduatiKagiri** [comment]
Good work so far. The code is very professional. But I think the following changes would make your website better.

- The `<main>` element should wrap everything in the body between the header and the footer
